// Renders an orb.toml for the orb-async-dev agent itself.
//
// Important: `[source]` points to this repo (orb-async-dev) — that's the agent's
// own code. The USER'S target repo (GITHUB_REPO) is cloned lazily at runtime
// inside the agent into ./work/, with git worktrees per task. Stack detection
// for the target repo happens at runtime, not here.

export interface OrbTomlInput {
  computerName: string;
  sourceGit: string;
  sourceBranch: string;
  runtime: string;
  disk: string;
  /** Port the webhook receiver listens on inside the Orb computer. */
  port: number;
  llm: {
    baseUrl: string;
    model: string;
    /** The secret env var name the agent reads, e.g. "ANTHROPIC_API_KEY" or "ANTHROPIC_AUTH_TOKEN". */
    secretName: "ANTHROPIC_API_KEY" | "ANTHROPIC_AUTH_TOKEN";
  };
  /** Non-secret env values written literally into [agent.env]. */
  env: Record<string, string>;
  /** Secret env placeholders; each key becomes `KEY = "${KEY}"` and must be supplied to POST /agents via org_secrets. */
  secrets: string[];
}

export interface DetectedDefaults {
  runtime: string;
  disk: string;
  port: number;
  sourceBranch: string;
}

export const DEFAULT_RESOURCES: DetectedDefaults = {
  runtime: "2GB",
  disk: "10GB",
  port: 8000,
  sourceBranch: "main",
};

/** Escape a string so it can be safely embedded in a double-quoted TOML value. */
export function tomlEscape(s: string): string {
  // TOML basic string escapes: \b \t \n \f \r \" \\
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t");
}

/** Render a [section] key=value block from a record; sorted keys for stability. */
function renderKv(record: Record<string, string>): string {
  return Object.keys(record)
    .sort()
    .map((k) => `${k} = "${tomlEscape(record[k]!)}"`)
    .join("\n");
}

/** Produce the orb.toml body. Stable ordering + minimal comments so diffs are readable. */
export function renderOrbToml(input: OrbTomlInput): string {
  const secretLines = input.secrets
    .slice()
    .sort()
    .map((name) => `${name} = "\${${name}}"`)
    .join("\n");

  const envLines = renderKv(input.env);

  return `# orb.toml — generated by deploy/orb-toml.ts for ${input.computerName}.
# Do not edit by hand; regenerate by re-running \`bun run deploy\`.

[agent]
name  = "${tomlEscape(input.computerName)}"
lang  = "typescript"
entry = "agent/orchestrator.ts"

[source]
git    = "${tomlEscape(input.sourceGit)}"
branch = "${tomlEscape(input.sourceBranch)}"

[build]
steps = [
    "bun install --frozen-lockfile",
]

[llm]
base_url = "${tomlEscape(input.llm.baseUrl)}"
model    = "${tomlEscape(input.llm.model)}"

[ports]
expose = [${input.port}]

[resources]
runtime = "${tomlEscape(input.runtime)}"
disk    = "${tomlEscape(input.disk)}"

[agent.env]
${envLines}${envLines && secretLines ? "\n" : ""}${secretLines}
`;
}

/** List of secret placeholders the agent needs at runtime. */
export function requiredSecrets(llmSecretName: OrbTomlInput["llm"]["secretName"]): string[] {
  return [llmSecretName, "GITHUB_TOKEN", "WEBHOOK_SECRET"];
}

/** Construct an OrbTomlInput from environment variables with sensible defaults. */
export function fromEnv(env: Record<string, string | undefined>): OrbTomlInput {
  const computerName = env.ORB_COMPUTER_NAME?.trim() || "orb-async-dev";
  const sourceGit = env.ORB_SOURCE_GIT?.trim() || "https://github.com/nextbysam/orb-async-dev";
  const sourceBranch = env.ORB_SOURCE_BRANCH?.trim() || DEFAULT_RESOURCES.sourceBranch;
  const runtime = env.ORB_RUNTIME?.trim() || DEFAULT_RESOURCES.runtime;
  const disk = env.ORB_DISK?.trim() || DEFAULT_RESOURCES.disk;
  const port = env.ORB_PORT ? Number.parseInt(env.ORB_PORT, 10) : DEFAULT_RESOURCES.port;

  const baseUrl = env.ANTHROPIC_BASE_URL?.trim() || "https://api.anthropic.com";
  const model = env.ANTHROPIC_MODEL?.trim() || "claude-opus-4-7";
  // If AUTH_TOKEN (proxy flow) is set, prefer it; otherwise assume native Anthropic key.
  const secretName = env.ANTHROPIC_AUTH_TOKEN ? "ANTHROPIC_AUTH_TOKEN" : "ANTHROPIC_API_KEY";

  const githubRepo = env.GITHUB_REPO?.trim();
  if (!githubRepo) throw new Error("GITHUB_REPO is required (format: owner/repo)");

  return {
    computerName,
    sourceGit,
    sourceBranch,
    runtime,
    disk,
    port,
    llm: { baseUrl, model, secretName },
    env: {
      NODE_ENV: "production",
      GITHUB_REPO: githubRepo,
      ANTHROPIC_BASE_URL: baseUrl,
      ANTHROPIC_MODEL: model,
      ORB_PORT: String(port),
    },
    secrets: requiredSecrets(secretName),
  };
}
